mindmap
    laptop
    ::icon(fa fa-laptop)
        wifi(Wifi)
        ::icon(fa fa-wifi)
        battery(Battery)
        ::icon(fa fa-battery)
        hard_drive(Hard Drive)
        ::icon(fa fa-hard-drive)
        memory(Memory)
        ::icon(fa fa-memory)
        microchip(Microchip)
        ::icon(fa fa-microchip)