sankey-beta
    First Element, Second Element, 99.9
    First Element, Third Element, 99.9
    First Element, Fourth Element, 99.9
    Second Element, Fifth Element, 99.9
    Third Element, Fifth Element, 99.9
    Fourth Element, Fifth Element, 99.9
    Sixth Element, Seventh Element, 99.9