sequenceDiagram
    participant 1 as one
    participant 2 as two
    1->2: Solid line without arrow
    1-->2: Dotted line without arrow
    1->>2: Solid line with arrowhead
    1-->>2: Dotted line with arrowhead
    1-x2: Solid line with a cross at the end
    1--x2: Dotted line with a cross at the end.
    1-)2: Solid line with an open arrow at the end (async)
    1--)2: Dotted line with a open arrow at the end (async)