%%{
  init: {
    'themeVariables': {
      'cScale0': '#ff0000',
      'cScaleLabel0': '#ffffff',
      'cScale1': '#00ff00',
      'cScale2': '#0000ff',
      'cScaleLabel2': '#ffffff'
    }
  }
}%%
timeline
    title Title
    section Group 1
        Time Line: Event
                : Event<br>Event
    section Group 2
        Time Line: Event
                : Event<br>Event
    section Group 3
        Time Line: Event
                : Event<br>Event
    section Group 4
        Time Line: Event
                : Event<br>Event
    section Group 5
        Time Line: Event
                : Event<br>Event
    section Group 6
        Time Line: Event
                : Event<br>Event
    section Group 7
        Time Line: Event
                : Event<br>Event
    section Group 8
        Time Line: Event
                : Event<br>Event
    section Group 9
        Time Line: Event
                : Event<br>Event
    section Group 10
        Time Line: Event
                : Event<br>Event
    section Group 11
        Time Line: Event
                : Event<br>Event
    section Group 12
        Time Line: Event
                : Event<br>Event