sequenceDiagram
    title Boxes
    box rgb(255, 0, 0) Box
        participant 1 as one
        participant 2 as two
    end
    box green Green Box
        participant 3 as three
        participant 4 as four
    end
    box blue Blue Box
        participant 5 as five
        participant 6 as six
    end