sequenceDiagram
    participant Mohamed as Mohamed
    participant Ahmed as Ahmed
    Mohamed->>Ahmed: Salam Ahmed, how are you?
    opt Opt
        Ahmed->>Mohamed: Salam Mohamed, Alhamdulillah!
    end