flowchart LR
    1(From)-->2(to)
    style 1 fill: #000000, stroke: #32cd32, stroke-width: 0.25rem
    style 2 fill: #000000, stroke: #32cd32, stroke-width: 0.25rem, stroke-dasharray: 3, width: 5rem, height: 5rem