classDiagram
    class Interface {
        <<interface>>
    }
    class Abstract {
        <<abstract>>
    }
    class Enumeration {
        <<enumeration>>
    }
    class sesrvice {
        <<service>>
    }