flowchart LR
    1:::red_box & 2:::green_box----->3:::blue_box
    classDef red_box stroke: #ff0000, height: 3rem, width: 3rem
    classDef green_box stroke: #00ff00, height: 4rem, width: 4rem
    classDef blue_box stroke: #0000ff, height: 5rem, width: 5rem