gantt
    title How many problems were solved?
    dateFormat X
    axisFormat %s
    section Mohamed
        1630: 0, 1630
    section Ahmed
        1277: 0, 1277
    section Mahmoud
        1069: 0, 1069