---
title: Branch
---
gitGraph
    commit "Message"
    commit id: "first_commit_id" msg: "Message"
    branch first_branch
    commit id: "second_commit_id" msg: "Message" type: REVERSE
    commit id: "third_commit_id" msg: "Message" type: NORMAL tag: "v1.0"
    branch "second_branch"
    commit id: "fourth_commit_id" msg: "Message" type: HIGHLIGHT tag: "v2.0"
