block-beta
    columns 1
    right<["Right"]>(right)
    left<["Left"]>(left)
    up<["Up"]>(up)
    down<["Down"]>(down)
    x<["X"]>(x)
    y<["Y"]>(y)
    left_and_right<["Left and Right"]>(left, right)
    up_and_down<["Up and Down"]>(up, down)
    up_and_right<["Up and Right"]>(up, right)
    up_and_left<["Up and Left"]>(up, left)
    down_and_right<["Down and Right"]>(down, right)
    down_and_left<["Down and Left"]>(down, left)
    up_left_right<["Up and Left and Right"]>(up, left, right)
    down_left_right<["Down and Left and Right"]>(down, left, right)
    up_down_left_right<["Up and Down and Left and Right"]>(up, down, left, right)