%%{
  init: {
    "quadrantChart": {
      "chartWidth": 850,
      "chartHeight": 850
    },
    "themeVariables": {
      "quadrant1TextFill": "#ffff00",
      "quadrant2TextFill": "#ff0000",
      "quadrant3TextFill": "#00ff00",
      "quadrant4TextFill": "#0000ff"
    }
  }
}%%
quadrantChart
    title Title
    x-axis First Column --> Second Column
    y-axis First Row --> Second Row
    quadrant-1 First Quadrant
    quadrant-2 Second Quadrant
    quadrant-3 Third Quadrant
    quadrant-4 Fourth Quadrant
    Point A: [0.0, 0.0]
    Point B: [0.2, 0.2]
    Point C: [0.4, 0.4]
    Point D: [0.6, 0.6]
    Point E: [0.8, 0.8]
    Point F: [0.99, 0.99]