sequenceDiagram
    Mohamed->>Ahmed: Salam Ahmed, how are you?
    activate Ahmed
    Ahmed-->>Mohamed: Salam Mohamed, Alhamdulillah!
    deactivate Ahmed
%% Another Solution
    Mohamed->>+Ahmed: Salam Ahmed, how are you?
    Ahmed-->>-Mohamed: Salam Mohamed, Alhamdulillah!