classDiagram
    direction LR
    class First {
        -String name
        -int age
        +String getName()
        +void setName(String name)
        +int getAge()
        +void setAge(int age)
    }

    class Second {
        -String job
        -Date birthDate
        +String getJob()
        +void setJob(String job)
        +Date getBirthDate()
        +void setBirthDate(Date birthDate)
    }

    click Second href "https://t.me/m3md69" "Mohamed Sadawy"