---
config:
  xyChart:
    width: 1000
    height: 1000
  themeVariables:
    xyChart:
      titleColor: "#32cd32"
---
xychart-beta horizontal
    title "Sales Revenue"
    x-axis [Muharram, Safar, Rabi-al-Awwal, Rabi-al-Thani, Jumada-al-Awwal, Jumada-al-Thani, Rajab, Sha-ban, Ramadan, Shawwal, Dhu-al-Qi-dah, Dhu-al-Hijjah]
    y-axis "Revenue (in $)" 4000 --> 11000
    bar [5000, 6000, 7500, 8200, 9500, 10500, 11000, 10200, 9200, 8500, 7000, 6000]
    line [5000, 6000, 7500, 8200, 9500, 10500, 11000, 10200, 9200, 8500, 7000, 6000]
