quadrantChart
    title Title
    x-axis First Column --> Second Column
    y-axis First Row --> Second Row
    quadrant-1 First Quadrant
    quadrant-2 Second Quadrant
    quadrant-3 Third Quadrant
    quadrant-4 Fourth Quadrant
    Point A: [0.0, 0.0]
    Point B: [0.2, 0.2]
    Point C: [0.4, 0.4]
    Point D: [0.6, 0.6]
    Point E: [0.8, 0.8]
    Point F: [0.99, 0.99]