block-beta
    round_edged_block("Round Edged Block")
    stadium_shaped_block(["Stadium-Shaped Block"])
    subroutine_shape[["Subroutine Shape"]]
    cylindrical_shape[("Cylindrical Shape")]
    circle_shape(("Circle Shape"))
    asymmetric >"Asymmetric Shape"]
    rhombus{"Rhombus Shape"}
    hexagon{{"Hexagon Shape"}}
    parallelogram[/"Parallelogram Shape"/]
    parallelogram_alt[\"Parallelogram Alt Shape"\]
    trapezoid[/"Trapezoid Shape"\]
    trapezoid_alt[\"Trapezoid Alt Shape"/]
    double_circle((("Double Circle")))