gantt
    title Title
    dateFormat YYYY-MM-DD
    axisFormat %d
    excludes thursday,friday
    tickInterval 1day
    weekday saturday
    section First
        start milestone: milestone, 2024-10-01, 0d
        one: 2024-10-03, 3d
        two: 5d
        three: 2024-10-04, 5d
        end milestone: milestone, 2024-10-31, 0d
    todayMarker stroke-width:0.25rem, stroke:#32cd32, opacity:1
%% You can disable todayMarker with `todayMarker off`