---
title: "Merge"
---
gitGraph
    commit id: "A"
    commit id: "B"
    commit id: "C"
    branch feature
    checkout feature
    commit id: "D"
    commit id: "E"
    commit id: "F"
    checkout main
%%    merge feature id: "Merge Commit" type: HIGHLIGHT
