---
title: "Rebase"
---
gitGraph
    commit id: "A"
    commit id: "B"
    commit id: "C"
    branch feature
    checkout feature
    commit id: "D"
    commit id: "E"
    commit id: "F"
%%    checkout main
%%    commit id: "D"
%%    commit id: "E"
%%    commit id: "F"
%%    commit id: "Rebase" type: HIGHLIGHT