%%{
  init: {
    "flowchart": {
      "defaultRenderer": "elk",
      "padding": 50
    }
  }
}%%
graph
    laptop["fa:fa-laptop"]
    laptop-->wifi[fa:fa-wifi]
    laptop-->battery(fa:fa-battery)
    laptop-->hard_drive(fa:fa-hard-drive)
    laptop-->ram(fa:fa-memory)
    laptop-->cpu(fa:fa-microchip)
    laptop-->keyboard(fa:fa-keyboard)
    laptop-->speaker(fa:fa-volume-up)