---
title: My Accounts
---
flowchart TB
    subgraph Telegram
        subgraph Private
            m4md24_telegram_account("@m4md24")
        end
        subgraph Channel
            barmajaa_telegram_channel("@Barmajaa")
            software_consulting_telegram_channel("@SoftwareConsulting")
        end
        subgraph Group
            barmajaa_telegram_group("@HadeethBarmajaa")
        end
    end
    subgraph Youtube
        barmajaa_youtube_channel("@Barmajaa")
    end
    subgraph Github
        m4md24_github_account("@m4md24")
    end
    subgraph MonkeyType
        m4md24_monkey_type_account("@m4md24")
    end
    click m4md24_telegram_account "https://t.me/m4md24" "Mohamed Sadawy" _blank
    click barmajaa_telegram_channel "https://t.me/Barmajaa" "Barmajaa" _blank
    click software_consulting_telegram_channel "https://t.me/SoftwareConsulting" "Software Consulting" _blank
    click barmajaa_telegram_group "https://t.me/HadeethBarmajaa" "HadeethBarmajaa" _blank
    click barmajaa_youtube_channel "https://www.youtube.com/@Barmajaa" "Barmajaa" _blank
    click m4md24_github_account "https://github.com/m4md24" "Mohamed Sadawy" _blank
    click m4md24_monkey_type_account "https://monkeytype.com/profile/m4md24" "Mohamed Sadawy" _blank