---
title: My Accounts
---
flowchart TB
    subgraph Telegram
        subgraph Private
            m3md69_telegram_account("@m3md69")
        end
        subgraph Channel
            nullexia_telegram_channel("@Nullexia")
            software_consulting_telegram_channel("@SoftwareConsulting")
            staunch_brotherhood_telegram_channel("@StaunchBrotherhood")
        end
        subgraph Group
            nullexia_telegram_group("@NullexiaCommunity")
            staunch_brotherhood_telegram_group("@StaunchBrotherhoodCommunity")
        end
    end
    subgraph Youtube
        nullexia_youtube_channel("@Nullexia")
    end
    subgraph Github
        m3md69_github_account("@m3md69")
    end
    subgraph MonkeyType
        m3md69_monkey_type_account("@m3md69")
    end
    click m3md69_telegram_account "https://t.me/m3md69" "Mohamed Sadawy" _blank
    click nullexia_telegram_channel "https://t.me/Nullexia" "Nullexia For Programming" _blank
    click software_consulting_telegram_channel "https://t.me/SoftwareConsulting" "Software Consulting" _blank
    click staunch_brotherhood_telegram_channel "https://t.me/StaunchBrotherhood" "Staunch Brotherhood" _blank
    click nullexia_telegram_group "https://t.me/NullexiaCommunity" "Nullexia For Programming Community" _blank
    click staunch_brotherhood_telegram_group "https://t.me/StaunchBrotherhoodCommunity" "Staunch Brotherhood Community" _blank
    click nullexia_youtube_channel "https://www.youtube.com/@NULLEXIA" "Nullexia For Programming" _blank
    click m3md69_github_account "https://github.com/m3md69" "Mohamed Sadawy" _blank
    click m3md69_monkey_type_account "https://monkeytype.com/profile/m3md69" "Mohamed Sadawy" _blank