sequenceDiagram
    participant Mohamed as Mohamed
    participant Ahmed as Ahmed
    Note right of Mohamed: Right Note of Mohamed
    Note left of Mohamed: Right Note of Mohamed
    Note over Mohamed, Ahmed: Note Over Mohamed and Ahmed
    Note right of Ahmed: Right Note of Ahmed
    Note left of Ahmed: Left Note of Ahmed