requirementDiagram
    requirement requirement_name {
        id: _id_
        text: _text_
        risk: low
        verifymethod: test
    }

    element element_name {
        type: typeName
        docref: documentReferences
    }

    designConstraint design_constraint_name {
        id: _id_
        text: _text_
        risk: low
        verifymethod: test
    }

    functionalRequirement functional_requirement_name {
        id: _id_
        text: _text_
        risk: low
        verifymethod: test
    }

    interfaceRequirement interface_requirement_name {
        id: _id_
        text: _text_
        risk: low
        verifymethod: test
    }

    performanceRequirement performance_requirement_name {
        id: _id_
        text: _text_
        risk: low
        verifymethod: test
    }

    physicalRequirement physical_requirement_name {
        id: _id_
        text: _text_
        risk: low
        verifymethod: test
    }

